name: akurat
description: "Mobile version of web news app www.akurat.co"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cached_query_flutter: ^1.0.1
  dio: ^5.4.0
  dio_mock_interceptor: ^1.0.1
  envied: ^0.5.2
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.1.0
  tuple: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  envied_generator: ^0.5.2

flutter:
  uses-material-design: true

  assets:
    - mock/
