name: akurat
description: "Mobile version of web news app www.akurat.co"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cached_query_flutter: ^1.0.1
  cached_storage: ^1.0.1
  carousel_slider: ^4.2.1
  dio: ^5.4.0
  dio_mock_interceptor: ^1.0.1
  envied: ^0.5.2
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_riverpod: ^2.4.9
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  lucide_icons: ^0.257.0
  shimmer: ^3.0.0
  websafe_svg: ^3.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  envied_generator: ^0.5.2

flutter:
  uses-material-design: true

  assets:
    - mock/
    - google_fonts/
    - assets/logo.svg
    - assets/akurat-icon.svg
